- maven/pom.xml
- Fixed remaining wrong version
> Release 4.9.0 - Release #2

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/Schedule2RAConverterTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
Closes #25
---
Task #25: Improve test coverage of Schedule2RAConverter
> Added test case for schedule 2 ra converter - (Task #25)

- de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsMemory2RDEP.dft
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizer.java
Closes #28 
---
Task #28: Add Test Case forcing POSynthesizer to create a timed
transition
> Added test case generating timed transitions - (Task #28)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/custom/UiSnippetFdirGenerator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ISynthesizer.java
- Closes #31
- Closes #33 
---
Task #31: Synthesizer that picks correct synthesizer depending on input
> Calling the delegate synthesizer in UI - (Task #31)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemanticsTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/FaultTreeEvaluator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/DelegateSynthesizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Closes #32
---
Task #32: Integrate PO DFT Semantics into evaluation workflow
> Refactoring to allow for po semantics in workflow - (Task #32)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/po/PONDDFTSemanticsTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolderTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
> Implemented helper method - (Task #54)

- de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
Closes #66
---
Task #66: Update Target Platform
> updated target platform - (Task #66)

- .mailmap
- bash/verify_commit_authors.sh
- known_authors.txt
Closes #72
---
Task #72: Add students to known_authors.txt
> Adding students - (Task #72)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAutomatonTest.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/RecoveryAutomatonFeatureProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/recoveryAutomata/MinimizeRAFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetSectionRecoveryAutomaton.java
- de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/RecoveryAutomaton.java
Closes #49
---
Task #18: Add Minimization into UI for Recovery Automata
> Feature/Task 18 Add Minimization

- bash/deploy_sourceforge.sh
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/IMarkovModelChecker.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/ModelCheckingStatistics.java
- de.dlr.sc.virsat.fdir.storm/src/de/dlr/sc/virsat/fdir/storm/runner/StormModelChecker.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConversionStatistics.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluationStatistics.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ARecoveryAutomatonMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/CleanMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/ComposedMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/FinalStateMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/MinimizationStatistics.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/OrthogonalPartitionRefinementMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/minimizer/PartitionRefinementMinimizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/SynthesisStatistics.java
- Created simple statistics classes
- Close #83
> Feature/Task 83 Create Statistics

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/RecoveryAutomatonFeatureProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/recoveryAutomata/MinimizeRAFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateAddFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateUpdateFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/transitions/TransitionAddFeature.java
> Feature/Task 56 Recovery Automaton diagram doesnt request for update

- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/recovery/RecoveryStrategy.java
> Feature/Task 90 Introduce canonic recovery state

- de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ASynthesizerExperiment.java
- de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/aiaa/AIAA2018Experiments.java
- de.dlr.sc.virsat.model.extension.fdir.experiments/src/de/dlr/sc/virsat/model/extension/fdir/experiments/ftscs/FTSCS2018Experiments.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
> Feature/Task 94 Use Statistics object for assertions / experiments

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/ASynthesizer.java
Sorry, I forgot to label the branch with feature/
In both ASynthesizer and Modularizer
---
Task #97: Implement basic event optimization option in modularizer
Closes #97
> Added setBEOptimizationOn - (Task #97)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRParametersGetterTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyDLTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FDIRParametersTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
- de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
- de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/command/ACreateAddArrayElementDetectionLevelsCommand.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableFDIRParametersDetectionLevels.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddArrayElementDetectionLevelsCommand.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddFDIRParametersCommand.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFDIRParametersDetectionLevels.java
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
- de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
- de.dlr.sc.virsat.model.extension.fdir/plugin.xml
- de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFDIRParameters.java
- de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFMECAEntry.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRExpressionEvaluator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/FDIRParametersGetter.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyDL.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPL.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/CutSet.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FDIRParameters.java
> Feature/Task 120 Automate setting the detectability levwl

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyDLTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPLTest.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntriesFMECAEntry.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
- de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
- de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/ACutSet.java
- de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFMECAEntry.java
- de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFault.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyDL.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/calculation/OpClassifyPL.java
> Feature/Task 116 Introduce UNKNOWN enum value

- de.dlr.sc.virsat.fdir.target/virsat_fdir_release.target
- de.dlr.sc.virsat.fdir.test.feature/feature.xml
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmerTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/trimmer/FaultTreeTrimmer.java
---
Task #136: add test case to fault tree trimmer
> Added test case - (Task #136)

- de.dlr.sc.virsat.fdir.test/pom.xml
- de.dlr.sc.virsat.fdir.test/src/de/dlr/sc/virsat/fdir/test/CoreAllTest.java
- de.dlr.sc.virsat.fdir.test/src/de/dlr/sc/virsat/fdir/test/ProjectAllTests.java
- launchers/VirSat FDIR All Tests.launch
Closes #144
---
Task #144: Execute CORE test cases
> Adjusted test structure - (Task #144)

- pom.xml
Closes #141
---
Task #141: Improve modularization for build time reduction
> Improved build modularization - (Task #141)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableCriticalityMatrixCriticalityMatrix.java
Closes #147
---
Task #147: Criticality Matrix creation causes exception in UI
> Fixed exceptions - (Task #147)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECATest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysisTest.java
- de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/Activator.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/handler/CreateFdirReportHandler.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/Activator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/CutSet.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/MCSAnalysis.java
- Using the proper activator to load the report
Closes #150
Closes #132
---
Task #150: Initaiting default FDIR report causes an exception
> Using correct Activator - (Task #150)

- de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
Closes #151
---
Task #151: Include criticality matrix in default FDIR report
> Added criticality matrix to the report template - (Task #151)

- de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
Closes #152
---
Task #152: Color FMECA entries according to criticality matrix in FDIR
Report
> Added highlighting rules to report template - (Task #152)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableAvailabilityAnalysisAvailabilityCurve.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableDetectabilityAnalysisDetectabilityCurve.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
Closes #157
---
Task #157: Limit maximum number of points shown in chart
> Limited maximum number of shown chart entries - (Task #157)

- de.dlr.sc.virsat.fdir.product/virsat_fdir.product
- Equinox.ds has been removed and replaced by Felix.scr
---
Task #161: Delivered product doesnt start
> Fixed starting configuration - (Task #161)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeDiagramToolBehaviorProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/DFTSemantics.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Closes #164
---
Task #164: Common cause failures in fault diagram not expanded correctly
> Fixed bug in diagram editor - (Task #164)

- bash/verify_commit_authors.sh
- known_authors.txt
- Fixing author verification.
- Added Christoph to known authors
Closes #166
> Added stripping of whitelines - (Task #166)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECATest.java
- de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
- de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/command/ACreateAddArrayElementCompensationCommand.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src-gen/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/AUiSnippetTableFMECAEntryCompensation.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddArrayElementCompensationCommand.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntryCompensation.java
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
- de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
- de.dlr.sc.virsat.model.extension.fdir/src-gen/de/dlr/sc/virsat/model/extension/fdir/model/AFMECAEntry.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECAEntry.java
Closes #159
---
Task #159: Rename proposed recovery action into Compensation
> Renamed property to "compensation" - (Task #159)

- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/command/CreateDeleteWithReferencingFDIRCategoryAssignmentsCommand.java
- Dont check for cascade deleted objects in the executability check for
the delete command
- Do check for them during the actual execution of the delete command
- This is necessary to ensure performance in the UI
Closes #57
---
Task #57: Performance bug in deletion in diagram
> Delayed cascade deletion - (Task #57)

- .project
- de.dlr.sc.virsat.fdir.branding.feature/.project
- de.dlr.sc.virsat.fdir.branding.ui/.project
- de.dlr.sc.virsat.fdir.core.test/.project
- de.dlr.sc.virsat.fdir.core/.project
- de.dlr.sc.virsat.fdir.docs.feature/.project
- de.dlr.sc.virsat.fdir.galileo.feature/.project
- de.dlr.sc.virsat.fdir.galileo.ide/.project
- de.dlr.sc.virsat.fdir.galileo.tests/.project
- de.dlr.sc.virsat.fdir.galileo.ui/.project
- de.dlr.sc.virsat.fdir.galileo/.project
- de.dlr.sc.virsat.fdir.license.feature/.project
- de.dlr.sc.virsat.fdir.p2updatesite/.project
- de.dlr.sc.virsat.fdir.product/.project
- de.dlr.sc.virsat.fdir.storm.test/.project
- de.dlr.sc.virsat.fdir.storm/.project
- de.dlr.sc.virsat.fdir.storm/META-INF/MANIFEST.MF
- de.dlr.sc.virsat.fdir.target/.project
- de.dlr.sc.virsat.fdir.test.feature/.project
- de.dlr.sc.virsat.fdir.test/.project
- de.dlr.sc.virsat.model.extension.fdir.experiments/.project
- de.dlr.sc.virsat.model.extension.fdir.feature/.project
- de.dlr.sc.virsat.model.extension.fdir.test/.project
- de.dlr.sc.virsat.model.extension.fdir.ui/.project
- de.dlr.sc.virsat.model.extension.fdir/.project
Closes #148
---
Task #148: Turn all projects into maven projects
> Updated project natures to maven projects - (Task #148)

- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/AvailabilityAnalysis.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
Closes #184
---
Task #184: Improve FMECA monitoring
> Improved monitoring of FMECA Analysis - (Task #184)

- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/command/CreateDeleteWithReferencingFDIRCategoryAssignmentsCommand.java
Closes #183
---
Task #183: Cascading delete command is missing executuablity check
> Added missing check for canExecute in command - (Task #183)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolderTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2dft/DFT2BasicDFTConverter.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FMECA.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/Fault.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTree.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Closes #187
---
Task #187: FMECA sometimes shows incorrect "infinite" in mean time to
failure
> Improved crosslinking nodes in different trees - (Task #187)

- de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
- de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
Closes #197
---
Task #197: Update concept to new DVLM v7
> Updated concept files - (Task #197)

- de.dlr.sc.virsat.model.extension.fdir.test/META-INF/MANIFEST.MF
- de.dlr.sc.virsat.model.extension.fdir.test/src-gen/de/dlr/sc/virsat/model/extension/fdir/test/AllTestsGen.java
- de.dlr.sc.virsat.model.extension.fdir.test/src-gen/de/dlr/sc/virsat/model/extension/fdir/validator/AStructuralElementInstanceValidatorTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/test/AllTests.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/validator/FaultValidatorTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/validator/StructuralElementInstanceValidatorTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/FaultTreeEdge.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHelper.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/validator/FaultValidator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/validator/StructuralElementInstanceValidator.java
Creating warnings if the from or the to properties of a fault tree edge are not set.
Closes #199
> Feature/task 195 create validator for 

- de.dlr.sc.virsat.model.extension.fdir/concept/concept.concept
- de.dlr.sc.virsat.model.extension.fdir/concept/concept.xmi
- de.dlr.sc.virsat.model.extension.fdir/concept/concept_v1_1.xmi
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Closes #200
---
Task #200: Set default failure rate to undefined
> Updated concept - (Task #200)

- de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_development.tmodel
- de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
- de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
Closes #202
---
Task #202: Set an icon for galileo dft importer / exporert
> Set icon for wizards - (Task #202)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeFeatureProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeAddFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeGraphicsFactory.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeUpdateFeature.java
Closes #130
---
Task #130: Make all gates have a name in the diagram editor
> Replaced type label with editable name label - (Task #130)

- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelChecker.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/BellmanMatrix.java
Moved method getInitialMTTFVector to BellmanMatrix.
Closes #219
---
Task #219: Extract initialMTTFVector to distinct location
> Extracted method getInitialMTTFVector - (Task #219)

- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
Fixed review remarks.
Closes #211
---
Task #211: Use Matrix operations in the MarkovScheduler class
> Fixed review remarks - (Task #211)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeDeleteFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableFMECAEntriesFMECAEntry.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableMCSAnalysisMinimumCutSetsCutSet.java
- Checking if a delete feature can be found for the desired sub-object
Closes #228
---
Task #228: Deleting a sub node in a fault tree causes NPEs
> Fixed NPE - (Task #228)

- build.xml
Changed http to https in buil script
---
Task #231: Change jacoco acquisition of jacoco.jar to https address
> Updated jacoco maven address - (Task #231)

- de.dlr.sc.virsat.fdir.docs.feature/src/docs/VirSat_FDIR_User_Manual.adoc
* Created basic description of software purpose
* Created basic description of main modeling workflow
* Created basic description of Fault Tree modeling
Closes #246
---
Task #246: FDIR User Manual Basic Usage chapter
> Created basic introduction - (Task #246)

- de.dlr.sc.virsat.fdir.product/virsat_fdir.product
Closes #249
---
Task #249: Dependencies issue in p2 repository
> Stopped delivering docker tooling feature - (Task #249)

- de.dlr.sc.virsat.model.extension.fdir.ui/plugin.xml
- de.dlr.sc.virsat.model.extension.fdir.ui/resources/apps/ft-generation/FDIRMechanismSelectionDialog.java
- de.dlr.sc.virsat.model.extension.fdir.ui/resources/apps/ft-generation/FaultTreeWithFDIRMechanismGenerator.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/handler/SoftwareFTGeneratorHandler.java
Closes #222
---
Task #222: Deliver App for generation fault trees
> Delivering java files for FT Generation - (Task #222)

- .travis.yml
- bash/deploy_sourceforge.sh
- bash/maven_build.sh
- bash/setup_environment.sh
---
Task #259: Fix and improve CodeCov Reporting
> Synchronized travis and bash files with CORE - (Task #259)

- de.dlr.sc.virsat.fdir.swtbot.test/src/de/dlr/sc/virsat/fdir/swtbot/test/GraphitiEditorTestCase.java
Cleaned up SWTBot methods that went into VirSat Core.
---
Task #269: SWTBot Cleanup Core pull up
> Cleaned up SWTBot methods - (Task #269)

- bash/deploy_sourceforge.sh
Closes #272
---
Task #272: Fix product deployment
> Removed sourceforge bin deployment - (Task #272)

- bash/deploy_sourceforge.sh
Closes #272
---
Task #272: Fix product deployment
> Fixed left over Core mention in bash script - (Task #272)

- NOTICE.md
- de.dlr.sc.virsat.fdir.branding.ui/about.html
- de.dlr.sc.virsat.fdir.branding.ui/plugin.xml
- de.dlr.sc.virsat.fdir.product/virsat_fdir.product
Carried out the licensing improvements described in the ticket
---
Closes Task #265: Improve Licensing and Copyright Information to protect DLR
Images and Logos
> Copyy & pasted licensing improvements - (Task #265)

- de.dlr.sc.virsat.model.extension.fdir.test/resources/galileo/csp1.dft
- de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoObs/obsObs2BeDelayed.dft
- de.dlr.sc.virsat.model.extension.fdir.test/resources/galileoRepair/delay1Repair.dft
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTStateTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/BasicSynthesizerTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft/analysis/DFTSymmetryChecker.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/events/IDFTEvent.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTModularization.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/BasicEvent.java
> Feature/task 310 improve testing of corner 

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeDiagramToolBehaviorProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeFeatureProvider.java
- Palette categories are now subdivided for gates and events
- Palette is now ordered alphabetically
Closes #322 
---
Task #319: Improve diagram editor palette
> Add palette improvement - (Task #319)

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/synthesizer/POSynthesizerTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Modularizer.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/Module.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/util/FaultTreeHolder.java
Closes #323
---
Task #323: Test Case Instability testTransformSand4ToExclusivePor
> Fixed instabilitiy issues - (Task #323)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeDiagramToolBehaviorProvider.java
Changed highlighting for selected elements in diagram editor.
Closes #318 
---
Task #318: Customize selection in diagram editor
> Changed highlighting in diagram editor - (Task #318)

- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/BellmanMatrix.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/iterator/BellmanIterator.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/iterator/IMatrixIterator.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/iterator/SPSIterator.java
- Removed unnecessary clone statements from bellman iterator
- Removed some unnecessary whitespaces in SPS iterator
- Moved getChange() logic into interface
Closes #329
---
Task #329: Remove unnecessary clone statements
> Refactored matrix iterators - (Task #329)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/BeanPropertyDirectEditValueFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeFeatureProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeAddFeature.java
Closes #333
---
Task #333: Direct editing features for any bean property
> Introduced general direct editing feature - (Task #333)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/command/CreateAddFDIRParametersCommand.java
Closes #230
---
Task #230: Allow for FDIRParameters to only be added at root level
> Added check to see if owner is root sei - (Task #230)

- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovSchedulerTest.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovScheduler.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/ScheduleQuery.java
Closes #339
---
Task #339: Make objective function in synthesis process configurable
> Added objectiveMetric property to ScheduleQuery- (Task #339)

- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/StronglyConnectedComponentTest.java
- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/algorithm/StronglyConnectedComponentFinderTest.java
- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/modelchecker/MarkovModelCheckerTest.java
- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovSchedulerTest.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovAutomaton.java
- de.dlr.sc.virsat.fdir.storm.test/src/de/dlr/sc/virsat/fdir/storm/runner/StormSchedulerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAStateSpaceGenerator.java
- launchers/VirSat FDIR Application.launch
- Implemented automatic addition of events
- Removed manual additions of events
Closes #347
---
Task #347: Automatically add new events to markov automaton
> Automatically adding events - (Task #347)

- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/matrix/iterator/SPSIteratorTest.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/MatrixFactory.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/matrix/iterator/SPSIterator.java
- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/AProbabilityCurve.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluatorTest.java
Closes #351
---
Task #351: MarkovAutomatonValueIterator produces incorrect result for
SPSIterator
> Extended SPS iterator with probabilistic lhandling - (Task #351)

- de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/metrics/MetricsDeriver.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/evaluator/DFTEvaluator.java
Closes #356
---
Task #356: Only generate markov automaton once per module
> Restructured evaluation flow - (Task #356)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentAddFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentMoveFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentUtil.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeFeatureProvider.java
Make Sticky notes reattachable/relocatable to fault tree nodes.
Closes #370 
---
Task #370: Make Stiky Notes reattachable/relocatable
> Make Sticky Notes reattachable/relocatable - (Task #370)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableAvailabilityAnalysisAvailabilityCurve.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableDetectabilityAnalysisDetectabilityCurve.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/snippet/UiSnippetTableReliabilityAnalysisReliabilityCurve.java
Closes #376
---
Task #376: Adjust to new JFreeChart dependencies
> Fixed imports  - (Task #376)

- build.xml
- de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/scheduler/MarkovSchedulerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModularizerTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/modularizer/ModuleTest.java
- maven/pom.xml
Closes #378
---
Task #378: Upgrade maven mojos
> Upgraded version of maven mojos - (Task #378)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
Reverts introduced change for border margin
---
> [Fix] revert border margin change

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/FaultTreeLayoutConnector.java
Closes #320 
---
Task #320: Increase border margin for auto layout
> Set border margin for auto layout - (Task #320)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentAddFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentMoveFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/comments/CommentUtil.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeLayoutFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/faultTreeNodes/FaultTreeNodeMoveFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/RecoveryAutomatonFeatureProvider.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateLayoutFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ra/features/states/StateMoveFeature.java
Closes #383 
---
Task #383: StickyNotes in RecoveryAutomatonDiagram
> Add sticky notes in RecoveryAutomatonDiagram - (Task #383)

- de.dlr.sc.virsat.model.extension.fdir.ui/resources/birt/savoir_fdir_report.rpttemplate
Fix a reporting bug in the FMECA section.
Closes #403 
---
Task #403: FMECA reporting bug
> FMECA reporting bug fix - (Task #403)

- de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_development.tmodel
- de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_integration.tmodel
- de.dlr.sc.virsat.fdir.target/tmodel-src/virsat_fdir_release.tmodel
- de.dlr.sc.virsat.fdir.target/virsat_fdir_development.target
- de.dlr.sc.virsat.fdir.target/virsat_fdir_integration.target
- de.dlr.sc.virsat.fdir.target/virsat_fdir_release.target
Closes #406
---
Task #406: Upgrade to new target platform structure
> Updated target models - (Task #406)

- de.dlr.sc.virsat.model.extension.fdir/META-INF/MANIFEST.MF
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/report/ReportHelper.java
Add report helper that can return fault tree diagram images for given
fault.
Closes #398
---
Task #398: Create FDIR Report Helper
> Reporting: Add report helper - (Task #398)

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/BeanPropertyDirectEditValueFeature.java
- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/diagram/ft/features/basicEvents/BasicEventsUpdateFeature.java
Closes #417
---
Task #417: Basic event failure rate does not update
> Fixed update check of basic event - (Task #417)

- de.dlr.sc.virsat.model.extension.fdir.feature/feature.xml
Closes #423
---
Task #423: Fix P2 Deployment by adding necessary BIRT dependencies.
> Fixed dependencies - (Task #423)

- de.dlr.sc.virsat.model.extension.fdir.feature/feature.xml
> Removed graphiti feature inclusion - Task #441

- de.dlr.sc.virsat.model.extension.fdir.ui/src/de/dlr/sc/virsat/model/extension/fdir/ui/handler/AOpenInDiagramEdiorHandler.java
> Fixed bad casting - Task #443

- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverterTest.java
- de.dlr.sc.virsat.model.extension.fdir.test/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysisTest.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAConverter.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFT2MAStateSpaceGenerator.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/DFTState.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/converter/dft2ma/semantics/StandardSPARESemantics.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ClaimAction.java
- de.dlr.sc.virsat.model.extension.fdir/src/de/dlr/sc/virsat/model/extension/fdir/model/ReliabilityAnalysis.java
- known_authors.txt
> Fixes Task #445
